"""initial_schema

Revision ID: 3aaca9acd8f5
Revises: 
Create Date: 2026-06-02 22:36:01.215159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaca9acd8f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('quests_completed', sa.Integer(), nullable=True),
    sa.Column('total_xp_earned', sa.Integer(), nullable=True),
    sa.Column('achievements_unlocked', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('inventory', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_progress_id'), 'player_progress', ['id'], unique=False)
    op.create_index(op.f('ix_player_progress_username'), 'player_progress', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_progress_username'), table_name='player_progress')
    op.drop_index(op.f('ix_player_progress_id'), table_name='player_progress')
    op.drop_table('player_progress')
    # ### end Alembic commands ###
