"""add achievements unlocked to player progress

Revision ID: 983ca693fd2c
Revises: 
Create Date: 2026-05-30 21:27:44.431833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '983ca693fd2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_index(op.f('name'), table_name='achievements')
    op.drop_table('achievements')
    op.add_column('player_progress', sa.Column('achievements_unlocked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_progress', 'achievements_unlocked')
    op.create_table('achievements',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('icon', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('xp_reward', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('required_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unlocked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('unlocked_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'achievements', ['name'], unique=True)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    # ### end Alembic commands ###
